package Helpers;

public enum ViewType {
    HOMEVIEW,
    SWITCHUSERVIEW,
    WELCOMEVIEW,
    INTROVIEW,
    NEWUSERVIEW,
    EDITUSERVIEW,
    VIDEOVIEW,
    MUSICVIEW,
    YOUTUBEVIEW,
    SPOTIFYVIEW,
    NEWFOLDERVIEW,
    EDITFOLDERVIEW,
    SETTINGSVIEW
}
